# .github/workflows/build.yml

name: Build, Export and Publish Next.js App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: |
          yarn install
          yarn build
      - name: Next Pages
        uses: anorcle/next-pages@v1.0
        with:
          # Next.js Export Directory
          inputDir: ./out
          # GitHub Pages Host Directory
          outputDir: ./docs
      - name: Commit and push changes
        run: |
          git config --global user.name "ahmetcanturker"
          git config --global user.email "ahmet@awaresol.com"
          git add -A
          git commit -m "New Build"
          git push